### ISSUE TITLE
Update old entries

### ISSUE THREAD

**Issue by j-selby** [citra-emu/citra-games-wiki#11]
Tagging: @Clector @Leo626 @TheKoopaKingdom @Desmondchaser27 @soukoba 

We have added new fields to our testcases - namely, CPU, GPU and operating system. Could you guys please open up PRs to fix that?

Take a look at the contribution guide for examples on how to do this.

**Comment by Clector** [comment]
Yes, I have already worked in updating my entries and also I added some new entries in my fork, all of them with the new fields for the testcases.
I"m going to open up a PR to fix that and add the new entries in a moment.

**Comment by Leo626** [comment]
Pushed my [changes](https://github.com/citra-emu/citra-games-wiki/commit/81a2c54632cbae08c194cb94aa685591255117ae).

**Comment by chris062689** [comment]
Does anyone else still have pending changes?
