### ISSUE TITLE
Wiki articles not displaying

### ISSUE THREAD

**Issue by AuraOfTheDawn** [citra-emu/citra-games-wiki#134]
Batman Arkham Origins: Blackgate 
Bravely Second
Etrian Odyysey IV: Legends Of The Titan
Hatsune Miku: Project Mirai DX
Metroid 2: Return of Samus
Petit Novel Series: Harvest December
Puzzle And Dragons X Kami no Shou
Resident Evil: Revelations
Resident Evil: The Mercenaries 3D
Tom Clancy's Splinter Cell: 3D
Zero Escape: Virtues Last Reward

Above titles are affected

**Comment by Schplee** [comment]
Fixed it. Issue was special characters in wiki page names.
