### ISSUE TITLE
Multiple testcase bug

### ISSUE THREAD

**Issue by Hexagon12** [citra-emu/citra-games-wiki#153]
A old testcase is always being displayed although there are newer ones. The correct behaviour would be to display the newest testcase in both the game page and the main page.

An example would be this: https://citra-emu.org/game/pokemon-super-mystery-dungeon/

**Comment by chris062689** [comment]
I think this is misleading, it's not always. This only happens when the test cases are out of order. The most recent test cases should be first in the list.
