### ISSUE TITLE
Wrong example in PR builder

### ISSUE THREAD

**Issue by CakeLancelot** [citra-emu/citra-games-wiki#158]
![image](https://user-images.githubusercontent.com/5341136/32575456-b3447352-c499-11e7-9dc8-1f259992270d.png)
The above example, ``GeForce GTX 960M`` is listed on the [game submission page](https://services.citra-emu.org/game/create/), but according to several PRs this is not correct. The correct format would be ``Nvidia GeForce GTX 960M``.

Sources:
https://github.com/citra-emu/citra-games-wiki/pull/149#discussion_r149372647
https://github.com/citra-emu/citra-games-wiki/pull/152#discussion_r149787905

**Comment by j-selby** [comment]
I don't think this is correct regardless - GTX is their product line. There are also GT GPUs, as well as a few others iirc which cannot be distinguished using the above described format.

**Comment by CakeLancelot** [comment]
> I don't think this is correct regardless - GTX is their product line. There are also GT GPUs, as well as a few others iirc which cannot be distinguished using the above described format.

Er, sorry. I've corrected the correction.. I meant ``Nvidia GeForce GTX 960M`` vs ``GeForce GTX 960M``

I just think the format is confusing - for example on an AMD card following the format on the PR builder  would we just list 'Radeon' and not 'AMD Radeon'?

**Comment by TheKoopaKingdom** [comment]
> I don't think this is correct regardless - GTX is their product line. There are also GT GPUs, as well as a few others iirc which cannot be distinguished using the above described format.
I might have to disagree. On [Nvidia's site](https://www.geforce.com/hardware) and [Wikipedia](https://en.wikipedia.org/wiki/GeForce_10_series#GeForce_10_.2810xx.29_series), they have `GTX` in the names of everything, so I would consider that to be the correct full name of the GPU.

**Comment by j-selby** [comment]
<https://www.geforce.com/hardware/desktop-gpus/geforce-gt-740>? that is most certainly not a GTX card.

**Comment by TheKoopaKingdom** [comment]
I should've clarified, my point is that if there is `GTX`, `GT`, or something similar, then it should be included in the game metadata.

**Comment by Hexagon12** [comment]
Fixed by 4b43168?

**Comment by j-selby** [comment]
No, this is a issue with the PR builder, which is in a different repo.

**Comment by j-selby** [comment]
Closing, as testcases are no longer submitted as part of the PR builder.
