### ISSUE TITLE
Bravely Default Inconsistent Metadata

### ISSUE THREAD

**Issue by TheKoopaKingdom** [citra-emu/citra-games-wiki#179]
The Bravely Default [metadata](https://github.com/citra-emu/citra-games-wiki/blob/master/games/bravely-default/game.dat) has lowercase TIDs, but the rest of the games wiki has uppercase TIDs.

**Comment by FearlessTobi** [comment]
This can be closed(?)

**Comment by Leo626** [comment]
Yes, uppercase TIDs are now enforced.
