### ISSUE TITLE
Phoenix Wright Duel Destinies improper compatibility listing

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra-games-wiki#233]
Its no where near perfect compatibility. In my opinion it should be in-between bad and ok since it boots but has really bad graphical glitches

tested on nightly-3c03da1

**Comment by robzombie91** [comment]
just tested on canary 95ed934 - Went from bad-ok to great - near perfect

**Comment by BreadFish64** [comment]
Right now the compatibility rating is just based on the latest rating reported in Citra, I would assume @Hexagon12 submitted that test case in Canary, you're more than welcome to submit a test case through Citra. I do think however, that Canary/Nightly builds should be distinguished in the list, so I'll bring it up.
