### ISSUE TITLE
Mario Party: Star Rushs wiki article doesn't get linked to it's page in the compat list

### ISSUE THREAD

**Issue by FearlessTobi** [citra-emu/citra-games-wiki#236]
There is already a wiki article existent for the game (https://github.com/citra-emu/citra-games-wiki/wiki/Mario-Party:-Star-Rush) but it doesn't get shown on the games page in the compat list because it expects the link to be https://github.com/citra-emu/citra-games-wiki/wiki/mario-party-star-rush.

**EDIT**: The same problem also seems to exist for MP: Island tour (https://github.com/citra-emu/citra-games-wiki/wiki/mario-party:-island-tour)

**EDIT 2**: The problem affects even more games. Here are all I could also find:

- https://github.com/citra-emu/citra-games-wiki/wiki/Shin-Megami-Tensei:-Devil-Survivor-Overclocked
- https://github.com/citra-emu/citra-games-wiki/wiki/Metroid-Prime---Federation-Force
- https://github.com/citra-emu/citra-games-wiki/wiki/Etrian-Odyssey-V-Beyond-the-Myth
- https://github.com/citra-emu/citra-games-wiki/wiki/Dragon-Ball-Z-Extreme-But%C5%8Dden

**Comment by Leo626** [comment]
There are issues with special characters in the wiki title. Most games have the colon in there which can cause issues so it shouldn't be included. We missed some of those in the review. I went ahead and removed them. Gonna wait and see if they are fixed when the website rebuilds. Strange thing is that I'm not sure about Etrian Odyssey V wiki.

**Comment by Leo626** [comment]
@FearlessTobi All wiki articles should be linked now.
