### ISSUE TITLE
Theatrhythm Final Fantasy - Curtain Call runs but is unplayable

### ISSUE THREAD

**Issue by Luneyes** [citra-emu/citra-games-wiki#275]
Hello there!
The game mostly works fine, no graphic problems, the speed is good and it runs at 60 FPS all the time on my computer. :D

The only huge problem is that the music have latency and is delaying itself further and further from the inputs seen on screen which makes the game unplayable! You can't play a rhythm game if the rhythm is wrong sadly...
I don't know why the music is delaying itself because the game runs perfectly at 60 all the time, maybe it has to be with the way audio is handled by the emulator?
I tried playing it on the last version downloaded today (16/03/18) on the website. I tried on both Canary and Nightly and they have the same issue... :/

I have no input delay though, I heard that was a thing but that bug seems to have been corrected! It's just the audio that's delayed now. ;)
I play with a Wacom Tablet and I also tried a controller, they both do the same so it change nothing to the problem. I also tried to mess with different settings but nothing seems to change anything audio related... :/

Thanks a lot for working on this emulator, you guys are awesome! I hope this problem may help you improve that amazing project! And have a nice day! :D

My specs:
OS: Windows 7 Ultimate 64 bits
CPU: Intel Core i7 2600K - Overclocked at 4.2GHz
Motherboard: ASRock Z77 Extreme4
RAM: 8 GB Corsair DDR3 666.54 MHz
GPU: NVIDIA GeForce GTX 760 Phantom - Overclocked at +10%

**Comment by Leo626** [comment]
Hi, I don't think this is the appropriate place for this issue. This issue tracker is for issues related to the compatibility database. For game related issues, you should probably ask in the forum or discord.
