### ISSUE TITLE
Resize image

### ISSUE THREAD

**Issue by krikic** [citra-emu/citra-games-wiki#28]
crop,resize images of Dragon Ball Fusions about game-title,map,combat scene,etc

**Comment by j-selby** [comment]
Closing. This is a issue tracker for issues within the current codebase. This should not be used for tracking your own changes.

Do that in a comment in your PR. Thanks!

**Comment by krikic** [comment]
I have prove game in all the regions, but work 100% perfect in themes sounds, audio, textures and graphics, but the unique inconvenient is save every game in citra. The option menu save status and load status isn't appear in menu of citra. Can't save the game.
