### ISSUE TITLE
Dragon Ball Fusions can't save progress game

### ISSUE THREAD

**Issue by krikic** [citra-emu/citra-games-wiki#29]
I have prove game in all the regions, but work 100% perfect in themes sounds, audio, textures and graphics, but the unique inconvenient is save every game in citra. The option menu save status and load status isn't appear in menu of citra. Can't save the game

**Comment by Schplee** [comment]
This issue tracker isn't for how well Citra emulates a game. It's for issues with the compatability database. Please open an issue in the main Citra repo, if there isn't already one.

**Comment by krikic** [comment]
It could  Load file, Load symbol maps and Recent files and can't right click on the files that are mentioned in that last category.

**Comment by krikic** [comment]
I wan to remove this issue.Game load perfect the progress finally and run at 100% all.
