### ISSUE TITLE
Games that start with T listed under L

### ISSUE THREAD

**Issue by Kloen** [citra-emu/citra-games-wiki#33]
I can uderstand the reason of TLOZ games being there, as well as Legend of Dark Witch.

But... This one should be here?
![image](https://user-images.githubusercontent.com/9112818/27324176-952a7f38-55a4-11e7-9be1-f67114894775.png)

**Comment by j-selby** [comment]
Yeah - we are looking to keep everything uniform. If we make exceptions on a per case basis things will get ugly quickly.

Thanks for pointing it out, but I'll be closing this one.
