### ISSUE TITLE
Some humble suggestions for improvng CONTRIBUTING.md.

### ISSUE THREAD

**Issue by Anadian** [citra-emu/citra-games-wiki#34]
So, I recently spent some time contributing to the code portions of the citra-games-wiki and just thought I'd take the time to make a case for some changes:
# Corrections
- CONTRIBUTING.md shows "USA","EUR", et cetera, (upper case) as valid values for the region keyword (under releases); however, In order for a game.dat file to pass the automated test on TravisCI, it necessitates that the region codes be lower case ("usa", "eur", et cetera): **CONTRIBUTING.md should be changed to reflect this**.
# Removals
- **Removing the descriptions from game.dat.** CONTRIBUTING.md recommends sourcing these descriptions from Wikipedia; this seems like a needless tedium and irrelevant to the actually goal of this wiki. We could just as well have keywords for publisher, developer, genre, but we don't, because they aren't necessary.
# Additions
- While we're on the topic of things that aren't necessary, I thought I'd make a case for **adding comments to the testcases**. I feel we should have comments for the same reason git-commits have messages: they offer an at-a-glance overview of what's actually changed between builds or a transition to different platform. Plus, they could be sourced and added to the actual wiki section.
- A lot can go wrong in the process of dumping and de-crypting a ROM, plus, for games that have received patches or updates over their lifespan, it remains ambiguous as to which version of the game was being tested. I believe **adding checksums to the testcases** would help alleviate these issues by offering a crystal-clear identifier for the ROM being used: distinguishing between good and bad ROMs as well as older and newer versions of a game.
# Changes
- The current TravisCI test requires at least one release and testcase for each game.dat file; I advocate for **removing this necessity** primarily because of "needs_system_archive" and "needs_shared_font" variables: having these documented is, itself, information that I would consider useful, even without an actual testcase.
- The current stand-in boxart, for eshop games, is to take a screenshot of the game's title screen. This makes it difficult to create a boxart.png for games with a particularly animated title screen and out-right impossible for games that, for compatibility reasons, don't render a title screen. **I suggest coming up with an alternative to this.**

So... you guys know where I stand on this. I thought I'd just make a case for why I ignored CONTRIBUTING.md where I did in my initial pull request. I'm alright with these suggestions being rejected but, regardless, I would very-much appreciate clarification on why these standards were decided in the first place.

**Comment by Subv** [comment]
I fully agree with all points except the one about game descriptions, I consider it important to show at least some basic information about the game in question. If we're going to take checksums into consideration, maybe we could automatically source game info from some online database.

**Comment by Anadian** [comment]
Thank you, @Subv. I also like the idea of sourcing from an external database.

**Comment by j-selby** [comment]
In terms of game descriptions:
- Wikipedia should not be an automated source of information - Wikipedia articles are not written in a format which conveys all the information which we might need (e.g going on about publishers, release dates, developers, etc, without potentially describing game content).
- I don't know of any other comprehensive game archive which can provide this kind of information - that is where the Citra wiki should come in, regardless.

I'm also going to have to disagree with the 'no release and testcase' clause. If you have tested the game, it is only one step further to gather that information - we are encouraging laziness with that one.

I do agree that a potential alternative to screenshots should be discussed in cases where that is not possible. As I've mentioned before, a image of an appropriate aspect ratio from Google, showing off the game logo could do the trick.

I am a big supporter of checksums, but that is something which will come later down the line - we preferably want checksums of original *encrypted* (and verified) ROMs rather then potentially modified encrypted ones.

**Comment by Anadian** [comment]
@j-selby "[W]e preferably want checksums of original encrypted (and verified) ROMs rather then potentially modified decrypted ones."

I fully understand wanting checksums to reflect the verified ROMs but, right now, Citra can only play unencrypted and, by extension, unverified ROMs. Ideally, Citra would be able to emulate 3DS games without any modifications to the game's ROM. The only immediate work-around for this, I can think of, would be to have Citra decrypt the ROM while it loads but that seems like it would take forever. I don't know if the ability to play encrypted ROMs is planned for future releases of Citra; for now, I think it may be worth adding a "decrypted_rom = true" field beneath the checksums: that would at least clarify whether a checksum, for a given testcase, is intended to reflect a verified or a personal dump.

In terms of boxart for eshop games, we might be able to use the "logos" from the game's Wikipedia page. e.g. [Mighty Gunvolt](https://en.wikipedia.org/wiki/File:Mighty_Gunvolt_Logo.png), [Gunman Clive](https://en.wikipedia.org/wiki/File:GunmanClive.jpg), and [Mutant Mudds](https://en.wikipedia.org/wiki/File:MutantMuddsTitle.jpg). These would be very convenient, since we're already going to the game's Wikipedia page to make the description. The only issues I could see are:
- The resolution and format of these images vary wildly.
- It stills leaves into question the more obscure eshop games which don't have a [Wikipedia page](https://en.wikipedia.org/wiki/List_of_Nintendo_3DS_games).

**Comment by wwylele** [comment]
> The only immediate work-around for this, I can think of, would be to have Citra decrypt the ROM while it loads but that seems like it would take forever. I don't know if the ability to play encrypted ROMs is planned for future releases of Citra

@Anadian fyi there is a plan to play encrypted rom, which is written in one of the github "project", and you can expect it to happen within one year I guess

**Comment by chris062689** [comment]
I think @Schplee will want to weigh in on this, we'll discuss these changes.

**Comment by Schplee** [comment]
> Removing the descriptions from game.dat.

I disagree that the descriptions should be removed. My opinion reflects what @j-selby wrote.

> adding comments to the testcases.

Testcases will be easily submitted by users, so by including a section for comments, a lot of garbage/low quality comments will more than likely be submitted. We'd rather have the summary in the wiki post reflect the status of the game. Users may update that as the game's compatibility changes.

> adding checksums to the testcase.

I support checksums of verified good dumps, but it is unnecessary until Citra is able to run encrypted CIAs. We want the most original, unmodified game files possible in order to promote the preservation of these games. As @wwylele said, this is already planned, so to include checksums of "unclean" games would be pointless.

> Removing the TravisCI test that requires at least one release and testcase for each game.dat file.

I disagree; My opinion reflects what @j-selby wrote.

>Take a screenshot of the game's title screen. I suggest coming up with an alternative to this.

For now, we will continue with the current method. However, we will look into finding an alternative/additional option for getting boxart for games that technically don't have boxes.
@j-selby has brought up something, but @bunnei will eventually want to re-haul the entire boxart process.

**Comment by TheKoopaKingdom** [comment]
Just to recap everything in this issue:
- [x] Correct capitalization of regions in CONTRIBUTING.md.
- [ ] Remove descriptions from game.dat (Rejected.).
- [ ] Add comments to testcases (Rejected.).
- [ ] Add checksums to testcases (Rejected for the time being.).
- [ ] Remove testcase requirement (Rejected.)
- [ ] Add alternative for E-Shop game boxart (Rejected for the time being.).
