### ISSUE TITLE
Game Compatibility List Won't Update

### ISSUE THREAD

**Issue by Secmess** [citra-emu/citra-games-wiki#452]
Basically: Game compatibility list won't update days after submission. The particular game I tested is Pokémon Sun with Citra Nightly 1064.

I tried to look everywhere, since I might miss something. But, surprisingly, I don't see a community as big as another emulators -- despite being a perfect ever-growing emu and is a recent/still popular platform.

**Comment by chris062689** [comment]
What is your forum username? I will check on this for you.

**Comment by Secmess** [comment]
It's "ArsenicBismuth".

**Comment by Secmess** [comment]
Is it no longer/not as actively maintained? I see that all of those compatibility lists are always has June as their latest.

While not a biggie once you understand that, it's pretty concerning though. I for one thought Pokemon USUM was way worse in comparison to Pokemon SM, but the community say that they're actually equal in performance.

**Comment by j-selby** [comment]
@Secmess it is actively maintained. Submissions can take time to come through, and there were build problems with the website before.

**Comment by Secmess** [comment]
Just checked the Compatibility list and now it's populated by very recent submission.
Though now my Citra gives "An error occured while sending the Testcase" (yes, also that misspelling).

But as @j-selby said, it might be specific build problem after all.

**Comment by chris062689** [comment]
Could you provide us a little more information? To make it easier to debug it may be easier for you to join our Discord.

**Comment by Secmess** [comment]
It seems the new problem is a very recent one, as reported by many other users:
https://community.citra-emu.org/t/an-issue-with-citra-emulators-report-compatibility/59835/

**Comment by chris062689** [comment]
This should now be resolved with the release of the new testcase submission process. 
Please reopen if you determine this issue crops up again.
