### ISSUE TITLE
Zero Escape: Virtue's Last Reward - Game FPS drop.

### ISSUE THREAD

**Issue by lonewolf329** [citra-emu/citra-games-wiki#51]
Using Nightly Build - 2e37ce0.
Game FPS drops to 4-5 during escape mode and sometimes during novel mode accompanied with audio stutter. 
Specs: Intel Core 2 Duo CPU e7500, Nvidia GeForce GT 640, 4GB RAM
Log File :https://pastebin.com/AD1zyEY1 .

**Comment by Hexagon12** [comment]
This is a database for games and not a support forum. Please use the forums for support requests. 

https://community.citra-emu.org/

Requesting to close this issue.
