### ISSUE TITLE
Circle Mod doesn't work in Metroid: Samus Returns

### ISSUE THREAD

**Issue by Snake-Spirit** [citra-emu/citra-games-wiki#549]
If i right understand Circle Mod allow free aim but it doesn't work. Aim just make a spurt to standard position. 
System: Windows 10 x64
version emulator: Nightly 1354 (2019-09-13)

**Comment by robzombie91** [comment]
Wrong place to put this issue, might wanna ask in the main Citra Build

**Comment by robzombie91** [comment]
Please close this issue if you have already asked in the main repo
