### ISSUE TITLE
Move all games into "games" folder

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra-games-wiki#64]
As the list of games becomes larger, it will become more difficult to navigate the list via the github ui (we will have over near 1000 entries by the time the DB is complete). We should move all game folders into a single folder so that non-compatibility files (contributions.md, etc) are more accessible.

**Comment by chris062689** [comment]
This is fine, but we'll have to coordinate with the following scripts:
- The import script within citra-web
- The PR builder.

**Comment by chris062689** [comment]
Fixed by a4faaa901defceaa25c59d3c93b48de0c00db4a6
