### ISSUE TITLE
Miitopia - Conflicting summary and compatibility rating

### ISSUE THREAD

**Issue by BynariStar** [citra-emu/citra-games-wiki#78]
From the summary:

>Miitopia has some problems in Citra. Graphically, the game suffers from minor issues ... It suffers from minor audio issues at times ... You may experience areas that one cannot progress in due to the lack of software keyboard emulation.

However, the compatibility is rated as perfect.

**Comment by Schplee** [comment]
@BynariStar Fixed via [c783d9f](https://github.com/citra-emu/citra-games-wiki/commit/c783d9f1e90d9cfd1af436d52099935fcdf62a83)
