### ISSUE TITLE
Story of Seasons: Trio of Towns - Incorrect compatibility rating

### ISSUE THREAD

**Issue by BynariStar** [citra-emu/citra-games-wiki#79]
The compatibility is rated as perfect despite the game requiring the use of the software keyboard, which is currently unimplemented. The summary doesn't mention this either.

**Comment by Schplee** [comment]
@BynariStar the software keyboard is stubbed, which is enough to beat the game completely (unverified). I will bump the rating down to "Great," as you're right in that it can't be considered "Perfect."
