### ISSUE TITLE
Fantasy Life - Conflicting summary and compatibility rating

### ISSUE THREAD

**Issue by BynariStar** [citra-emu/citra-games-wiki#80]
From the summary:

>Fantasy Life has few problems in Citra. Graphically, the game suffers from minor issues, but requires decent hardware to obtain mediocre speed. It suffers from minor audio issues at times, but this does not hinder gameplay in any way.

However, the compatibility is rated as bad.

**Comment by Schplee** [comment]
@BynariStar fixed via [ac7444e](https://github.com/citra-emu/citra-games-wiki/commit/ac7444ee9cfcc001fafcd93e82df96060ce5a0a6)
